FILENAME		=		dynamic_array/push_back_dynamic_arr\
						dynamic_array/destroy_dynamic_arr\
						dynamic_array/new_dynamic_arr\
						utils/mlx_utils\
						utils/mlx_hook\
						utils/color\
						utils/handle_error\
						material/metal\
						material/new_random_material\
						material/new_material\
						material/lambertian\
						material/dielectric\
						material/emmisive\
						object_array/get_object\
						object_array/clear_object_arr\
						object_array/add_object\
						object_array/hit_object_arr\
						object_array/init_object_arr\
						main\
						pdf/light_arr_pdf\
						pdf/cosine_pdf\
						pdf/mixture_pdf\
						texture/checker\
						texture/solid\
						texture/texture\
						camera/init_camera\
						object/plane_pdf\
						object/tube_hit\
						object/disk\
						object/cylinder\
						object/cone_lateral\
						object/cone_lateral_pdf\
						object/cone\
						object/cone_lateral_hit\
						object/cone_pdf\
						object/plane\
						object/point_light_pdf\
						object/tube\
						object/sphere_pdf\
						object/point_light\
						object/cylinder_pdf\
						object/utils\
						object/tube_pdf\
						object/sphere\
						object/disk_pdf\
						parsing/parse_element_solid\
						parsing/parse_element_extra\
						parsing/build_element_cone\
						parsing/build_element_solid\
						parsing/ft_atof\
						parsing/parse_scene\
						parsing/parse_value\
						parsing/build_element_cylinder\
						parsing/utils\
						ray/reflected_ray\
						ray/ray\
						ray/diffused_ray\
						ray/primary_ray\
						ray/refracted_ray\
						scene/init_scene\
						scene/manage_color\
						scene/render_scene\
						scene/flush_scene\
						scene/gamma_correction\
						scene/shading\
						